# Generated by Django 4.1.2 on 2022-10-27 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HngSlackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=70)),
                ('backend', models.BooleanField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bio', models.TextField()),
            ],
        ),
    ]
